#include <string.h>
#include <stdlib.h>
#include "lua5.1/lua.h"
#include "lua5.1/lauxlib.h"
int write_string(lua_State *L) {
	const char* filename = lua_tostring(L, 1);
	int table_size = lua_tointeger(L, 2);
	const char* c = "-- Automatically generated by sprite-tool.\n\n";
	char* write = malloc(strlen(c) + 1);
	strcpy(write, c);
	for(unsigned int i = 0; i < table_size; i++) {
		lua_pushinteger(L, i + 1);
		lua_gettable(L, 3);
		const char* rope = lua_tostring(L, -1);
		char* temp = malloc(strlen(write) + strlen(rope) + 1);
		strcpy(temp, write);
		strcat(temp, rope);
		free(write);
		write = temp;

		lua_pop(L, 1);
	}
	char* final = malloc(strlen(write) + 1);
	strcpy(final, write);
	free(write);
	FILE* file = fopen(filename, "w");
	if(fputs(final, file) == EOF) {
		return 0;
	}
	fclose(file);
	free(final);
	return 1;
}
static const struct luaL_Reg functions[] = {
	{"write_string", write_string},
	{NULL, NULL}
};

int luaopen_libs_writer(lua_State *L) {
	luaL_register(L, "writer", functions);
	return 1;
}
